version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube

  jupyter:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
    ports:
      - "80:8888"
    volumes:
      - ./scripts:/opt/odc/scripts
      - ./data:/opt/odc/data
      - ./notebooks:/notebooks
    shm_size: 1g
    command: jupyter notebook --allow-root --ip="*" --NotebookApp.token='secretpassword'
