version: '3'

services:
  postgres:
    image: postgis/postgis:12-2.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  jupyter:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_NO_SIGN_REQUEST=true
      - STAC_API_URL=https://explorer.sandbox.dea.ga.gov.au/stac/
      - CIABPASSWORD=${CIABPASSWORD:-secretpassword}
      - STAC_API_URL=https://explorer.sandbox.dea.ga.gov.au/stac/
    links:
      - postgres:postgres
    ports:
      - "80:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./tests:/tests
      - ./utils:/utils
      - ./products.csv:/products.csv
    restart: always
  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    links:
      - postgres:postgres
